spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.stream.config.BindingServiceConfiguration
      - org.springframework.cloud.stream.function.FunctionConfiguration
      - org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration
      - org.springframework.cloud.stream.config.BindingsEndpointAutoConfiguration
      - org.springframework.cloud.stream.config.ChannelsEndpointAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    consumer:
      group-id: payment-execution-biz-${random.uuid}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.arcpay.payment.paymentexecution.domain.event,com.arcpay.compliance.domain.event,com.arcpay.settlement.domain.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  temporal:
    test-server:
      enabled: true

namastack:
  outbox:
    enabled: true

arcpay:
  policy-service:
    url: http://localhost:8081
  identity-service:
    url: http://localhost:8080
  settlement-service:
    url: http://localhost:8084
  security:
    service-token: test-service-token
