spring:
  datasource:
    url: jdbc:tc:postgresql:16:///arcpay_identity_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  temporal:
    test-server:
      enabled: true
